### ISSUE TITLE
Closing my Github account

### ISSUE THREAD

**Issue by ghost** [lgierth/promise.rb#40]
Hi all,

I'm the original author of promise.rb - it's great to see it's still of use to so many people. I intend to close my Github account and here's a plan how to do that without causing any trouble for promise.rb. These steps can hopefully be done in less than 10 minutes.

1. Create `lgierth2` org
2. Add all current committers to that org
3. Move promise.rb to `lgierth2` org
4. Rename `lgierth` account to something else
5. Rename `lgierth2` org to `lgierth`
6. Done

Does this sound good? If so, I'd follow through with this on 1 July.

Thanks!

**Comment by dylanahsmith** [comment]
Sounds good

**Comment by lgierth-old** [comment]
It is done - I sent you an owner invite, and you might have to double check that any webhooks and CI are still functioning. If there's anything that I need to fix, don't hesitate to email me at lars dot mylastname at gmail.

So long and thanks for all the fish!
