### ISSUE TITLE
Outstanding performance improvements?

### ISSUE THREAD

**Issue by rmosolgo** [lgierth/promise.rb#46]
I remember @arthurschreiber hunting some good performance wins on his own branch a _loooong_ time ago, and I can't remember if the all got merged here, or if some of them are still in https://github.com/arthurschreiber/promise.rb/branches somewhere. Does anyone know? 

cc @ahoglund, do you mind checking if GitHub still runs a custom sha of this library? (Or maybe it's running a Rubygems version by now, like I said, I can't remember...) Thanks!

**Comment by ahoglund** [comment]
@rmosolgo - github/github runs the `promise.rb` version as a dependency of `graphql-batch`. At this time those versions are:

```
graphql-batch (0.4.3.20.g211b11a)
┊ graphql (>= 1.3, < 2)
┊ promise.rb (~> 0.7.2)
```

**Comment by dylanahsmith** [comment]
https://github.com/lgierth/promise.rb/pull/34 was an iteration on some of that performance work.  Although, it looked like there was planned follow-up work on top, but not corresponding PR that I see

**Comment by rmosolgo** [comment]
Ahh -- ok, thanks for sharing that detail, @ahoglund. It looks like that commit _was_ released: https://github.com/Shopify/graphql-batch/commit/211b11a (in GraphQL-Batch 0.5.0). So, I guess my memory was a bit out of date 😅 Thanks for looking into it!
