### ISSUE TITLE
bundle install fails on this repo

### ISSUE THREAD

**Issue by dylanahsmith** [lgierth/promise.rb#6]
The Gemfile for this repo is using devtools with an unspecified version or git reference.  The Gemfile.devtools requires `gem 'rspec',      '~> 2.99.0'` but all the released version of devtools expect 3.x

Here is the error message from `bundle install`: 

```
Bundler could not find compatible versions for gem "rspec":
  In Gemfile:
    rspec (~> 2.99.0)

    devtools was resolved to 0.1.4, which depends on
      rspec (~> 3.4.0)

    fuubar was resolved to 1.2.1, which depends on
      rspec (~> 2.0)
```

**Comment by lgierth** [comment]
hey, thanks for reporting this -- I'm not sure what happened to rspec 2.99, maybe they removed it from rubygems when they released 3.0? anyhow i'd happily accept a patch to fix this mess. I haven't really done any ruby work for the past year-or-so.
